config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/liked_posts', to: 'users#liked_posts'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users, except: %i[destroy create] do
    member do
      get 'follows'
      get 'followers'
    end
  end
  root 'authentication#show_form'
  get 'authentication/show_form', as: :show_form_in
  post 'authentication/look_for'
  get 'authentication/add_nickname', as: :nickname
  post 'authentication/nickname_exists'
  get 'authentication/code_confirmation'
  post 'authentication/confirmation'
  get 'authentication/open_sess', to: 'authentication#open_sess', as: "open_sess"
  get '/posts/hashtag/:name', to: 'posts#hashtags', as: :hashtag

  resources :posts do
    resources :comments, module: :posts
  end
  
  get 'likes_toggle/:post_id', to: 'users#likes_toggle', as: :likes_toggle
  get 'follow_toggle/:user_id', to: 'users#follow_toggle', as: :follow_toggle
  get 'is_private/:user_id', to: 'users#is_private', as: :is_private
  get 'ask_follow_toggle/:user_id', to: 'users#ask_follow_toggle', as: :ask_follow_toggle
  get 'searches', to: 'searches#index', as: 'searches'
  get 'phones', to: 'searches#phone_search', as: 'phone_search'
  get 'hashtags', to: 'searches#hashtag_search', as: 'hashtag_search'
  delete 'delete_avatar/:upload_id', to: 'users#delete_avatar', as: :delete_avatar
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :phone, presence: true, length: { is: 10 }, uniqueness: true, numericality: { only_integer: true }
  validates_uniqueness_of :nickname, allow_blank: true
  validates :nickname, length: { minimum: 5 }, on: :update
  has_many :posts, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_many :comments, dependent: :nullify

  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:phone]

  has_and_belongs_to_many :follows, dependent: :destroy,
                                    join_table: :followers,
                                    class_name: 'User',
                                    foreign_key: :follower_id,
                                    association_foreign_key: :follow_id

  has_and_belongs_to_many :followers, dependent: :destroy,
                                      join_table: :followers,
                                      class_name: 'User',
                                      foreign_key: :follow_id,
                                      association_foreign_key: :follower_id

  has_and_belongs_to_many :inviteds, dependent: :destroy,
                                     join_table: :invites,
                                     class_name: 'User',
                                     foreign_key: :invited_id,
                                     association_foreign_key: :inviter_id

  has_and_belongs_to_many :inviters, dependent: :destroy,
                                     join_table: :invites,
                                     class_name: 'User',
                                     foreign_key: :inviter_id,
                                     association_foreign_key: :invited_id

  has_and_belongs_to_many :liked_posts, dependent: :nullify,
                                        join_table: :likes,
                                        class_name: 'Post'

  def email_required?
    false
  end

  def email_changed?
    false
  end

  include PgSearch

  pg_search_scope :search, 
    against: [:nickname, :phone],
    using: {tsearch: {dictionary: "english"}},
    associated_against: { users: [:nickname, :phone]},
    ignoring: :accents

  def self.text_search(query)
    if query.present?
      where("nickname ilike :q", q: "%#{query}%")
    else
      where(nil)
    end
  end

  def self.phone_search(query)
    if query.present?
      where("phone ilike :q", q: "%#{query}%")
    else
      where(nil)
    end
  end

  def online?
    updated_at > 30.minutes.ago
  end

  def update_with_password(params, *options)
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = if params[:password].blank? || valid_password?(current_password)
      update_attributes(params, *options)
    else
      self.assign_attributes(params, *options)
      self.valid?
      self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
      false
    end

    clean_up_passwords
    result
end
  

  private

  symbols = ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', ':', ';', '<', '>', '-', '_']
  def error_messages
    puts 'your nickname has to be more symbols' if nickname.length < 5
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  layout 'authentication'
  before_action :user_log_in?

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    render layout: 'user'
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      redirect_back(fallback_location: posts_path)
    end
  end

  def likes_toggle
    post = Post.find_by(id: params[:post_id])
    current_user.liked_posts << post
    redirect_back(fallback_location: posts_path)
  end

  def follow_toggle
    user = User.find_by(id: params[:user_id])
    # if user.is_private == false
      if current_user.follows.include?(user)
        current_user.follows.delete(user)
      else
        current_user.follows << user
      end
      redirect_back(fallback_location: posts_path)
    # else
    #   ask_follow_toggle
    # end
  end

  def ask_follow_toggle
    user = User.find_by(id: params[:user_id])
    if current_user.inviters.include?(user)
      current_user.inviters.delete(user)
    else
      current_user.inviters << user
    end
    redirect_back(fallback_location: posts_path)
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.follows
    render :index
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render :index
  end

  def liked_posts
    @posts = current_user.liked_posts.all.uniq
  end

  def delete_avatar
    @avatar = ActiveStorage::Attachment.find_by(id: params[:upload_id])
    @avatar.purge
    redirect_back(fallback_location: posts_path)
  end

  def is_private
    if @current_user.is_private
      current_user.update(is_private: false)
    else
      current_user.update(is_private: true)
    end
    redirect_back(fallback_location: edit_user_path(current_user))
  end

  private

  def user_params
    params.require(:user).permit(:nickname)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<div class="settings">
  <div class="form-in-authentication">
    <h3 class="names-sectors">
      Личная информация
    </h3>
    <%= form_with scope: :user,  url: user_path(current_user), method: :put, local: true do |f| %>
    <div class="edit-nickname">
      <p class="hint-input">
        Имя пользователя
      </p>
      <%= f.text_field :nickname, :value => current_user.nickname, :class => "input_information" %>
    </div>
    <%= f.submit 'Сохранить изменения', class: 'block-send-information pt-1' %>
    <% end %>
    <div class="account-settings">
      <h3 class="names-sectors">
        Аккаунт
      </h3>
      <hr class="line-sector">
      <%= link_to users_liked_posts_path, class: 'links-in-setting' do %>
      <div class="flex-between">
        <span>
          <%= image_tag 'icons/heart.png', class: 'imgtag-png' %> Понравившиеся публикации
        </span>
        <i class="fa fa-chevron-right text-right"></i>
      </div>
      <% end %>
      <hr class="line-sector">
      <%= link_to is_private_path(current_user), class: 'links-in-setting' do %>
        <div class="flex-between">
          <span class="d-flex justify-content-start">
            <div class="d-inline-block">
              <%= image_tag 'icons/lock.png', class: 'imgtag-png' %>
            </div>
            <div class="d-inline-block ml-2">Сделать профиль приватным 
            <p class='hint-settings'> Просматривать ваш профиль и посты <br> могут только одобренный вами люди </p>
          </div>
        </span>
        <% if current_user.is_private == false %>
            <%= show_svg('off.svg') %>
          <% else %>
            <%= show_svg('on.svg') %>
          <% end %>
      </div>
    <% end %>
   </div>
   <div>
    <h3 class="names-sectors">Конфиденциальность <br> и безопасность</h3>
    <hr class="line-sector">
    <%= link_to "#", class: 'links-in-setting' do %>
    <div class="flex-between">
      <span class="d-flex justify-content-start">
        <div class="d-inline-block"><%= image_tag 'icons/visibility.png', class: 'imgtag-png' %></div>
        <div class="d-inline-block ml-2">Видеть меня по номеру телефона
          <p class='hint-settings'> Другие пользователи могут искать  <br> вас по номеру телефона </p>
        </div>
      </span>
      <%= image_tag 'icons/off.png' %>
    </div>
    <% end %>
    <hr class="line-sector">
    <%= link_to "#", class: 'links-in-setting' do %>
    <div class="flex-between">
      <span><%= image_tag 'icons/user.png', class: 'imgtag-png' %> Черный список</span>
      <i class="fa fa-chevron-right text-right"></i>
    </div>
    <% end %>
    <hr class="line-sector">
    <%= link_to "#", class: 'links-in-setting reset-password' do %>
    <div class="flex-between">
      <span><%= image_tag 'icons/PIN.png', class: 'imgtag-png' %> Сбросить пароль</span>
      <i class="fa fa-chevron-right text-right"></i>
    </div>
    <% end %>
    <hr class="line-sector">
    <%= link_to registration_path(current_user), data: { confirm: "Вы уверены, что хотите удалить Ваш аккаунт?" }, method: :delete, class: 'links-in-setting delete-accaunt' do %>
    <div class="flex-between  mb-5">
      <span><%= image_tag 'icons/cross.png', class: 'imgtag-png' %> Удалить аккаунт</span>
      <i class="fa fa-chevron-right text-right"></i>
    </div>
    <% end %>
  </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content"> 
      <div class="modal-exit">
        <p class="text-center m-0">Вы уверены, что хотите выйти?</p>
      </div>
      <div class="modal-footer">
        <%= link_to "Отмена", "#", class: 'link-exit no-exit', "data-dismiss" => "modal" %>
        <span class="border-exit"></span>
        <%= link_to "Выйти", destroy_user_session_path, method: :delete,  class: 'link-exit exit' %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="mt-4 container">
  <% @users.each do |user| %> 
    <div class="d-flex align-items-center justify-content-between friend">
      <%= link_to(user_path(user)) do %>
        <div class="d-flex align-items-center">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar, class: "avatar_in_post rounded-circle float-center mr-3"%> 
          <% else %>
            <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center  mr-3") %>
          <% end %>
          <div class="nickname_follows">@<%= user.nickname %></div>
        </div>
      <% end %>


      <% if current_user != user %>
        
      <% if user.in?(current_user.follows) %>
        <a href="#" data-toggle="modal" data-target="#exampleModalCenter<%= user.id %>" class="btn-follows">
          Отписаться
        </a>
        <div class="modal fade" id="exampleModalCenter<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content"> 
              <div class="modal-exit">
                <p class="text-center m-0">Вы точно хотите отписаться от пользователя?</p>
              </div>
              <div class="modal-footer">
                <%= link_to "Отмена", "#", class: 'link-exit no-exit', "data-dismiss" => "modal" %>
                <span class="border-exit"></span>
                <%= link_to 'Отписаться', follow_toggle_path(user), class: "text-primary link-exit" %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <%= link_to 'Подписаться', follow_toggle_path(user), class: "btn-follows" %>
      <% end %>

      <% end %>
      
    </div>
  <% end %>
</div>

    

app/views/users/liked_posts.html.erb
<% @posts.each do |post| %>
    <section class='container mt-2 mb-2'>
      <div class="card">
        <div>
          <% if current_user.id == post.user.id %>
            <div class="dropdown">
              <button class="dropdown-toggle border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ...
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'изменить', edit_post_path(post), class: "dropdown-item" %>
                <%= link_to 'удалить', post_path(post), method: :delete, class: "dropdown-item", remote: true %>
              </div>
            </div>
          <% end %>
        </div> 
        <div class="card-body">
          <div class="post_section">
            <div class="post_section">
              <div class="position-relative pr-2">
                <div class="active_user_mini pl-2">
                  
                  <div>
                  <% if post.user.online? %>
                      <i class="fa fa-circle text-success"></i>
                      <% else %>
                      <i class="fa fa-circle text-danger"></i>
                    <% end %>
                    <% if post.user.avatar.attached? %>
                      <%= image_tag post.user.avatar, class: "avatar_in_post rounded-circle float-center" %> 
                    <% else %>
                      <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center") %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="w-100">
              <div class="post_section">
                <p class="nickname_text m-0">
                  <%= link_to user_path(post.user), class: "text-body nickname_text" do %>
                    @<%= post.user.nickname %>
                  <% end %>
                </p>
                <p class="time post_writed">
                  <span class="pr-2 pl-2"><%= show_svg('line2.svg') %></span> <%= post.created_at.strftime("%d.%m.%Y, %H:%M") %>
                </p>
              </div>
              <div class="wrap">
                <div class="card-text post_writed text_wrap mt-3"><%= render_with_hashtags(post.description)  %> </div>
              </div>
              <div class="border-0 align-self-center mt-2">     
                <% if post.attachment.attached? %>
                  <% if post.attachment.content_type.include?("image") %>
                    <div class="card_body"> <%= image_tag post.attachment, class: "image text-center"  %> </div>
                  <% else %>
                    <%= video_tag url_for(post.attachment), :controls => true , class: "video" %>
                  <% end %>
                <% end %>
              </div>
              <div class="card-body border-0 align-self-center">
                <div class="post_section mobile_post_section">
                  <div class="comments">
                    <%= link_to(post_path(post)) do %>
                      <p class="icon_text text-center">
                        <span class="none-mobile"><%= show_svg('comment.svg') %></span>
                        <span class="none-desktop"><%= show_svg('comment _mobile.svg') %></span>
                        <%= post.comments.count %> <span class="none-mobile">комментариев</span> 
                      </p> 
                    <% end %>            
                  </div>
                  <div class="likes">
                    <%= link_to(likes_toggle_path(post)) do %>
                      <p class="icon_text  text-center"> 
                        <% if post.likes.ids.include?(current_user.id) %>
                          <span class="none-mobile"><%= show_svg('tenge_active.svg') %></span>
                          <span class="none-desktop"><%= show_svg('tenge_acktive_mobile.svg') %></span>
                        <% else %>
                          <span class="none-mobile"><%= show_svg('tenge_grey.svg') %></span>
                          <span class="none-desktop"><%= show_svg('tenge_mobile.svg') %></span>
                        <% end %>
                        <%= post.likes.count %> <span class="none-mobile">лайкбонусов</span>
                      </p>
                    <% end %>
                  </div>
                </div>
              </div>
              <% if post.comments.any? %>
              <% comment = post.comments.last %>
                <div class="border_on_comment">
                  <div class="post_section">
                    <div class="pr-2">
                      <div class="position-relative">
                        <% if comment.user.avatar.attached? %>
                          <%= image_tag comment.user.avatar, class: "photo_comment rounded-circle float-center" %> 
                        <% else %>
                          <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo_mini rounded-circle float-center") %>
                        <% end %>
                      </div>
                    </div>
                    <div>
                      <div class="post_section">
                        <%= link_to(user_path(post.user)) do %>
                          <p class="nickname_text_comment">
                            @<%= comment.user.nickname %>
                          </p>
                        <% end %>  
                        <p class="time post_writed none-mobile"> | <%= comment.created_at.strftime("%d.%m.%Y, %H:%M") %></p>                      
                        
                      </div>
                      <div class="wrap">
                        <div class="card-text post_writed text_comment text_wrap mt-1"><%= comment.body %> </div>
                        <div class="time post_writed none-desktop"><%= comment.created_at.strftime("%d.%m.%Y, %H:%M") %></div>
                      </div>
                    </div>
                  </div>  
                </div>
              <% end %>  
            </div>
          </div>  
        </div>
        <% if post.comments.any? %>
          <div class="text-center">
            <%= link_to(post_path(post)) do %>
              <p class="all_comments m-0">
                Все комментарии
              </p>
            <% end %>
          </div>
        <% end %>
      </div>
    </section>
  <% end %> 
  <div class="container text-center pb-2 pt-2">
    <div class="text-center pb-1">   
      <%= show_svg('smile.svg') %>
    </div> 
  </div>

app/views/users/show.html.erb
<div class="back_container shadow-sm">
<div class="user_show container">
  <div class="center-position about_user">
    <div class="">
      <div class="media-body flex-container"> 
        <div class="card-body position">
          <div class="position-relative">
          <div class="active_user fa_circle position-relative">
            <% if @user.online? %>
              <i class="fa fa-circle text-success"></i>
            <% else %>
              <i class="fa fa-circle text-danger"></i>
            <% end %>
          </div>
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, class: "photo rounded-circle float-center"%> 
            <% else %>
              <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo rounded-circle float-center") %>
            <% end %>
          </div>
          <% if current_user == @user %> 
            <button type="button" class="close mt-0 h5 position-relative" aria-label="Close">
              <div aria-hidden="true">
                <%= link_to(edit_user_registration_path) do %>
                  <div class="square">
                    <span class="none-desktop pr-3"> <%= show_svg('edit_button_mobile.svg') %></span>
                    <span class="none-mobile pr-4"><%= show_svg('edit_button.svg') %></span>
                   
                  </div>
                <% end %>
              </div>
            </button>
          <% end %>  
        </div>
        <div class="user">
          <% if @user.nickname.nil? %>s
              <h6> <%= @user.phone %> </h6>
          <% else %>
              <h6 > @<%= @user.nickname %> </h6>
          <% end %>
          <section class="btn-group center-position">
            <div class="text-center blocks_under_avatar"><%= link_to(followers_user_path(@user)) do %>
              <%= show_svg('friens_icon.svg') %>
                <div class="counter">
                  <p class="count"><%= @user.followers.count %></p>
                  <p class="counter"> подписчиков </p>
                </div>
              <% end %>
            </div>
            <%= show_svg('line3.svg') %>
            <div class="text-center blocks_under_avatar"><%= link_to(follows_user_path(@user)) do %>
              <%= show_svg('friens_icon_2.svg') %>
                <div class="counter">
                  <p class="count"><%= @user.follows.count %></p>
                  <p class="counter"> подписки </p>
                </div>
              <% end %>
            </div>
            <%= show_svg('line3.svg') %>
            <div class="text-center blocks_under_avatar"><%= link_to(user_path(@user)) do %>
              <%= show_svg('tenge_icon_active.svg') %>
                <div class="counter">
                  <p class="count"><%=  @user.liked_posts.count %></p>
                  <p class="counter"> бонусов </p>
                </div>
              <% end %>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
  <div>
  <% if current_user == @user %>
    <section class="container ">
      <div class="new_post form_in_users_show">
        <div class="avatar_mini">
          <div>
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, class: "photo_mini rounded-circle float-center"%> 
            <% else %>
              <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo_mini rounded-circle float-center") %>
            <% end %>
          </div>
        </div>
        <div class="post_write">
          <%= form_with url: posts_path, scope: :post, local: true do |f| %>
            <%= f.text_field :description, placeholder: 'Расскажите что-нибудь народу. Напишите пост;)', type: "text", class: 'form-control', autocomplete: "off" %>
            <%f.file_field :picture %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <% f.submit %> 
          <% end %>
        </div>          
      </div>
    </section>
  <% end %> 
  <% if current_user != @user %>
    <div class="container padding_bot flex-container">
      <% if @user.in?(current_user.follows) %>
        <a href="#" data-toggle="modal" data-target="#exampleModalCenter" class="unsubscribe">
          Отписаться
        </a>
      <% else %>
        <% if current_user != @user %>
          <%= link_to 'Подписаться', follow_toggle_path(@user), class: "send-information m-0" %>
        <% end %>
      <% end %>

      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content"> 
            <div class="modal-exit">
              <p class="text-center m-0">Вы точно хотите отписаться от пользователя?</p>
            </div>
            <div class="modal-footer">
              <%= link_to "Отмена", "#", class: 'link-exit no-exit', "data-dismiss" => "modal" %>
              <span class="border-exit"></span>
              <%= link_to 'Отписаться', follow_toggle_path(@user), class: "text-primary link-exit" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>  
  <div class="users_posts">
  <% if current_user ==@user || current_user != @user && @user.is_private == false || (@user.is_private == true && @user.followers.include?(current_user) == true)%>
    <% @posts.each do |post| %>
      <section class='container mt-2 mb-2'>
        <div class="card">
          <div>
            <% if current_user == @user %>
              <div class="dropdown">
                <button class="dropdown-toggle border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ...
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'изменить', edit_post_path(post), class: "dropdown-item" %>
                  <%= link_to 'удалить', post_path(post), method: :delete, class: "dropdown-item", remote: true %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="post_section">
              <div class="pr-2">
                <div class="position-relative pl-2">
                  <% if @user.avatar.attached? %>
                    <%= image_tag @user.avatar, class: "avatar_in_post rounded-circle float-center" %> 
                  <% else %>
                    <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center") %>
                  <% end %>
                </div>
              </div>
              <div>
                <div class="post_section">
                  <p class="nickname_text mb-1 pr-1">
                    <% if @user.nickname.nil? %>
                      <%= @user.phone %>
                    <% else %>
                      @<%= @user.nickname %>
                    <% end %>
                  </p>
                  <p class="time post_writed"><span class="pr-2 pl-2"><%= show_svg('line2.svg') %></span> <%= post.created_at.strftime("%d.%m.%Y, %H:%M") %></p>
                </div>
                <div class="wrap">
                  <div class="card-text post_writed text_wrap"><%= render_with_hashtags(post.description) %> </div>
                </div>
                <div>
                  <div class="">     
                    <% if post.attachment.attached? %>
                      <% if post.attachment.content_type.include?("image") %>
                        <div class="card_body"> <%= image_tag post.attachment, class: "image text-center"  %> </div>
                      <% else %>
                        <%= video_tag url_for(post.attachment), :controls => true , class: "video" %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="under_post_section border-0 align-self-center">
                    <div class="post_section mobile_post_section">
                      <div class="comments">
                      <%= link_to(post_path(post)) do %>
                        <p class="icon_text text-center">
                          <span class="none-mobile"><%= show_svg('comment.svg') %></span>
                          <span class="none-desktop"><%= show_svg('comment _mobile.svg') %></span>
                          <%= post.comments.count %> <span class="none-mobile">комментариев</span> 
                        </p> 
                      <% end %>            
                      </div>
                      <div class="likes">
                        <%= link_to(likes_toggle_path(post)) do %>
                          <p class="icon_text  text-center"> 
                            <% if post.likes.ids.include?(current_user.id) %>
                            <span class="none-mobile"><%= show_svg('tenge_active.svg') %></span>
                            <span class="none-desktop"><%= show_svg('tenge_acktive_mobile.svg') %></span>
                            <% else %>
                            <span class="none-mobile"><%= show_svg('tenge_mobile.svg') %></span>
                            <span class="none-desktop"><%= show_svg('tenge_mobile.svg') %></span>
                            <% end %>
                            <%= post.likes.count %> <span class="none-mobile">лайкбонусов</span>
                          </p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>  
          </div>
        </div>
      </section>
    <% end %>
    <div class="container text-center pb-2 pt-2">
      <div class="text-center pb-1">   
        <%= show_svg('smile.svg') %>
      </div> 
      <p class="smile">Пиши исчо, постов больше нет</p>
    </div>
  <% elsif current_user != @user && (@user.is_private == true && @user.followers.include?(current_user) == false ) %>
    <% nil %>
  <% end %>
  </div>
  </div>
  </div>
</div>