config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/liked_posts', to: 'users#liked_posts'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users, except: %i[destroy create] do
    member do
      get 'follows'
      get 'followers'
    end
  end
  root 'authentication#show_form'
  get 'authentication/show_form', as: :show_form_in
  post 'authentication/look_for'
  get 'authentication/add_nickname', as: :nickname
  post 'authentication/nickname_exists'
  get 'authentication/code_confirmation'
  post 'authentication/confirmation'
  get 'authentication/open_sess', to: 'authentication#open_sess', as: "open_sess"
  get '/posts/hashtag/:name', to: 'posts#hashtags', as: :hashtag

  resources :posts do
    resources :comments, module: :posts
  end
  
  get 'likes_toggle/:post_id', to: 'users#likes_toggle', as: :likes_toggle
  get 'follow_toggle/:user_id', to: 'users#follow_toggle', as: :follow_toggle
  get 'is_private/:user_id', to: 'users#is_private', as: :is_private
  get 'ask_follow_toggle/:user_id', to: 'users#ask_follow_toggle', as: :ask_follow_toggle
  get 'searches', to: 'searches#index', as: 'searches'
  get 'phones', to: 'searches#phone_search', as: 'phone_search'
  get 'hashtags', to: 'searches#hashtag_search', as: 'hashtag_search'
  delete 'delete_avatar/:upload_id', to: 'users#delete_avatar', as: :delete_avatar
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :user_activity

  protected

  def configure_permitted_parameters
    added_attrs = %i[phone password password_confirmation remember_me avatar nickname]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def user_log_in?
    redirect_to root_path unless user_signed_in?
  end

  def log_in?
    if user_signed_in?
      redirect_to posts_path
    end
  end

  def after_sign_in_path_for(_resources)
    if current_user.nickname
      posts_path
    else
      nickname_path
    end
  end
  
  def after_sign_up_path_for(resource)
    nickname_path
  end

  def after_inactive_sign_up_path_for(resource)
    nickname_path
  end



  private

  def user_activity
    current_user.try :touch
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application/_navbar.html.erb
<nav class="navbar fixed-top top_nav">
  <div class="container">
    <div class="bg-white navbar-expand-md nav-justified">
      <% if params[:action] == 'show' && params[:controller] == 'users' %>
        <div class="">
            <%= link_to(posts_path, class: 'text-primary') do %>
              <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад в ленту</span> </p>
            <% end %>
        </div>
      <% elsif params[:action] == 'show' && params[:controller] == 'posts' %>
        <div class="">
          <%= link_to(posts_path, class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад</span>  </p>
          <% end %>
        </div>
      <% elsif params[:action] == 'hashtags' && params[:controller] == 'posts' %>
        <div class="">
          <%= link_to(posts_path, class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад в ленту</span>  </p>
          <% end %>
        </div>
      <% elsif params[:action] == 'edit' && params[:controller] == 'posts' %>
        <div class="h6">
          <%= link_to(user_path(current_user), class: 'text-primary') do %> 
            <p class="nav_link pt-4"><%= show_svg('union.svg') %> Назад в профиль </p>
          <% end %>
        </div>
      <% elsif params[:action] == 'edit' && params[:controller] == 'users' %>
        <div class="">
          <%= link_to(user_path(current_user), class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад к профилю</span> </p>
          <% end %>
        </div>
      <% elsif params[:action] == 'follows' && params[:controller] == 'users' %>
        <div class="">
          <%= link_to(user_path(@user), class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад</span>  </p>
          <% end %>
        </div>
      <% elsif params[:action] == 'followers' && params[:controller] == 'users' %>
        <div class="">
          <%= link_to(user_path(@user), class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад</span>  </p>
          <% end %>
        </div>
      <% elsif params[:action] == 'new' && params[:controller] == 'posts'%>
        <div class="">
          <%= link_to(posts_path, class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад</span> </p>
          <% end %>
        </div>
      <% elsif params[:action] == 'index' && params[:controller] == 'searches' %>
        <div class="">
          <%= link_to(posts_path, class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад</span>  </p>
          <% end %>
        </div>
      <% elsif params[:action] == 'phone_search' && params[:controller] == 'searches' %>
        <%= link_to(searches_path, class: 'text-primary') do %> 
          <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад</span>  </p>
        <% end %>
      <% else %>
        <div class="h6 m-0">
          <%= link_to(user_path(current_user)) do %> 
            <div class="post_section">
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, class: "photo_back rounded-circle float-center"%> 
              <% else %>
                <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo_mini rounded-circle float-center") %>
              <% end %>
              <div class="nav_nick pl-1 none-mobile">
                Привет, 
                <% if current_user.nickname.nil? %>
                  <%= current_user.phone %>
                <% else %>
                  <%= current_user.nickname.capitalize %>!
                <% end %>
              </div>
            </div> 
          <% end %>
        </div>
      <%end %>  
      
      <div class="h6 m-0">
        <% if params[:action] == 'show' && params[:controller] == 'users' %>
          <p class="m-0 center-navbar"> Профиль </p>
        <% elsif params[:action] == 'edit' && params[:controller] == 'users'%>
          <p class="m-0 center-navbar"> Настройки </p>
        <% elsif params[:action] == 'new' && params[:controller] == 'posts'%>
          <p class="m-0 new_post_navbar"> Новый пост</p>
        <% elsif params[:action] == 'follows' && params[:controller] == 'users'%>
          <p class="m-0 follows">Подписки</p>
        <% elsif params[:action] == 'followers' && params[:controller] == 'users'%>
          <p class="m-0 follows">Подписчики</p>
        <%end %>
      </div>
      <% if user_signed_in? %>
        <div>
          <% if params[:action] == 'show' && params[:controller] == 'users' && current_user == @user%>
            <%= link_to(posts_path, class: 'text-primary') do %> 
              <span class="none-desktop pr-3"><%= show_svg('Group-mobile.svg') %></span>
              <span class="none-mobile pr-4"><%= show_svg('Group.svg') %></span>
            <% end %>
            <%= link_to(edit_user_path(current_user), class: 'text-primary') do %>
              <span class="none-mobile"><%= show_svg('shape.svg') %></span>
              <span class="none-desktop"><%= show_svg('settings-mobile.svg') %></span>
            <% end %>
          <% elsif params[:action] == 'show' && params[:controller] == 'users' && current_user != @user %>
            <span class="none-desktop pl-5"><%= show_svg('menu-mobile.svg') %></span>
            <span class="none-mobile pl-4"><%= show_svg('menu.svg') %></span>
          <% elsif params[:action] == 'edit' && params[:controller] == 'users'%>
            <%= link_to '#', class: 'navbar-nav h6 pl-1 sort', "data-toggle" => "modal", 'data-target' => '#exampleModalCenter' do %>
              <div class="sign-out">
                Выйти <%= show_svg('logout.svg') %>
              </div>
            <% end %>
          <% elsif params[:action] == 'new' && params[:controller] == 'posts'%>
            <% nil %>
          <% elsif params[:action] == 'index' && params[:controller] == 'posts'%>
              <%= link_to(searches_path) do %> 
                <span class="none-desktop pr-3"><%= show_svg('search-mobile.svg') %></span>
                <span class="none-mobile pr-4"><%= show_svg('search.svg') %></span>
              <%end%>
              <%= link_to(posts_path, class: 'text-primary') do %> 
                <span class="none-desktop"><%= show_svg('Group-mobile.svg') %></span>
                <span class="none-mobile pr-4"><%= show_svg('Group.svg') %></span>
              <% end %>
                <span class="none-desktop"><%= link_to image_tag("add.png", class: "add_post ml-3" ), new_post_path %></span>
                <span class="none-mobile pr-4"><%= link_to 'Написать пост', new_post_path, class: "btn btn-primary btn-md mb-1 ml-1 gradient pl-4 pr-4 none-mobile" %></span>
          <% else %>
            <% nil %>
          <% end %>
        <% end %> 
      </div>            
    </div>
  </div>
</nav>

app/views/layouts/application/_navbarapp.html.erb
<nav class="navbar fixed-top top_nav nav_app">
  <div class="container">
    <div class="bg-white navbar-expand-md nav-justified">
      <% if params[:action] == 'index' && params[:controller] == 'searches' %>
        <div class="">
          <%= link_to(posts_path, class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад</span>  </p>
          <% end %>
        </div>
        <% elsif params[:action] == 'phone_search' && params[:controller] == 'searches' || params[:action] == 'hashtag_search' && params[:controller] == 'searches' %>
          <%= link_to(searches_path, class: 'text-primary') do %> 
            <p class="nav_link m-0"><%= show_svg('union.svg') %> <span class="none-mobile">Назад</span>  </p>
          <% end %>
        <% elsif params[:action] == 'edit' && params[:controller] == 'registrations' %>
            <%= link_to(user_path(current_user), class: 'text-primary') do %> 
            <p class="nav_link pt-4"><%= show_svg('union.svg') %> Назад в профиль </p>
          <% end %>
      <%end %>  
      <% if params[:action] == 'index' && params[:controller] == 'searches' %>
        <div class="h6 m-0 search_div">
          <%= form_tag searches_path, method: :get do %>
            <%= text_field_tag :query, params[:query], autofocus: true, placeholder: "Поиск по аккаунтам", class: 'search_control' %>
            <% submit_tag "Search", name: nil %>
          <% end %>
        </div>
      <% elsif params[:action] == 'phone_search' && params[:controller] == 'searches' %>
        <div class="h6 m-0 search_div">
          <%= form_tag phone_search_path, method: :get do %>
            <div class="inline"> 
              <div class="cod_country">+7(</div>
              <%= text_field_tag :query, params[:query], autofocus: true, class: 'search_control phone_mask' %>
            </div>
            <% submit_tag "Search", name: nil %>
          <% end %>
        </div>
        <% elsif params[:action] == 'hashtag_search' && params[:controller] == 'searches' %>
          <div class="h6 m-0 search_div">
            <%= form_tag hashtag_search_path, method: :get do %>
              <%= text_field_tag :query, params[:query], autofocus: true, placeholder: "Поиск публикаций по меткам", class: 'search_control' %>
              <% submit_tag "Search", name: nil %>
            <% end %>
          </div>
      <%end %>     
    </div>
    <% if params[:action] == 'edit' && params[:controller] == 'registrations' %>
            <% nil %>
    <% else %>
      <div class="m-0 search_link">  
        <ul class="navbar-nav navbar-expand-sm between">
          <li class="nav-item "> <%= link_to 'Популярное', '#', class: "nav-link"; %> </li>
          <li class="nav-item "> <%= link_to 'Номера', phone_search_path, class: "nav-link"; %> </li>
          <li class="nav-item active_link"> <%= link_to 'Люди', searches_path, class: "nav-link active"; %> </li>
          <li class="nav-item "> <%= link_to 'Хэштеги', hashtag_search_path, class: "nav-link"; %> </li>
        </ul> 
      </div>
    <% end %>
  </div>
</nav>