config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/liked_posts', to: 'users#liked_posts'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users, except: %i[destroy create] do
    member do
      get 'follows'
      get 'followers'
    end
  end
  root 'authentication#show_form'
  get 'authentication/show_form', as: :show_form_in
  post 'authentication/look_for'
  get 'authentication/add_nickname', as: :nickname
  post 'authentication/nickname_exists'
  get 'authentication/code_confirmation'
  post 'authentication/confirmation'
  get 'authentication/open_sess', to: 'authentication#open_sess', as: "open_sess"
  get '/posts/hashtag/:name', to: 'posts#hashtags', as: :hashtag

  resources :posts do
    resources :comments, module: :posts
  end
  
  get 'likes_toggle/:post_id', to: 'users#likes_toggle', as: :likes_toggle
  get 'follow_toggle/:user_id', to: 'users#follow_toggle', as: :follow_toggle
  get 'is_private/:user_id', to: 'users#is_private', as: :is_private
  get 'ask_follow_toggle/:user_id', to: 'users#ask_follow_toggle', as: :ask_follow_toggle
  get 'searches', to: 'searches#index', as: 'searches'
  get 'phones', to: 'searches#phone_search', as: 'phone_search'
  get 'hashtags', to: 'searches#hashtag_search', as: 'hashtag_search'
  delete 'delete_avatar/:upload_id', to: 'users#delete_avatar', as: :delete_avatar
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @searches = User.text_search(params[:query])
    sort_users
  end

  def phone_search
    mask_delete
    @phones = User.phone_search(@query)
    sort_users
  end

  def hashtag_search
    @hashtags = Tag.hashtag_search(params[:query])
  end

  private
  def mask_delete
    if params[:query] != nil && params[:query].length >= 5
      arr = []
      arr = params[:query].split(') ')
      arr[1] = arr[1].split(' ')
      @query = arr.join('')
    elsif params[:query] != nil && params[:query].length < 4
      @query = params[:query]
    end
    return @query 
  end
  def sort_users
    @followers_uniq = current_user.follows
  
  end
end

app/views/searches/hashtag_search.html.erb
<div id="users" class="container">
  <% @hashtags.each do |hashtag| %>
    <h2>
      <%= link_to hashtag.name, hashtag_path(hashtag.name) %>
    </h2>
  <% end %>
</div>

app/views/searches/index.html.erb
<div id="users" class="container">
  <% if params[:query] == nil %>
    <div class="recomendation">
      Рекомендации
    </div>
      <% if @followers_uniq.present? %>
        <% @followers_uniq.each do |user| %>
          <% unless current_user == user %>  
            <div class="d-flex align-items-center justify-content-between friend">
              <%= link_to(user_path(user.id)) do %>
                <div class="d-flex align-items-center">
                  <% if user.avatar.attached? %>
                    <%= image_tag user.avatar, class: "avatar_in_post rounded-circle float-center mr-3"%> 
                  <% else %>
                    <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center  mr-3") %>
                  <% end %>
                  <div class="nickname_follows">@<%= user.nickname %></div>
                </div>
              <% end %>
              <% if current_user != user %>  
                <% if user.in?(current_user.follows) %>
                  <a href="#" data-toggle="modal" data-target="#exampleModalCenter<%= user.id %>" class="btn-follows btn-search">
                    Отписаться
                  </a>
                  <div class="modal fade" id="exampleModalCenter<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content"> 
                        <div class="modal-exit">
                          <p class="text-center m-0">Вы точно хотите отписаться от пользователя?</p>
                        </div>
                        <div class="modal-footer">
                          <%= link_to "Отмена", "#", class: 'link-exit no-exit', "data-dismiss" => "modal" %>
                          <span class="border-exit"></span>
                          <%= link_to 'Отписаться', follow_toggle_path(user), class: "text-primary link-exit" %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% else %>
                  <%= link_to 'Подписаться', follow_toggle_path(user), class: "btn-follows btn-search" %>
                <% end %>
              <% end %>
            </div>
          <%end%>  
        <%end%>
      <%end%>
      
  <%else%>
    <% @searches.each do |user| %>
      <div class="d-flex align-items-center justify-content-between friend">
        <%= link_to(user_path(user.id)) do %>
          <div class="d-flex align-items-center">
            <% if user.avatar.attached? %>
              <%= image_tag user.avatar, class: "avatar_in_post rounded-circle float-center mr-3"%> 
            <% else %>
              <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center  mr-3") %>
            <% end %>
            <div class="nickname_follows">@<%= user.nickname %></div>
          </div>
        <% end %>
        <% if current_user != user %>  
          <% if user.in?(current_user.follows) %>
            <a href="#" data-toggle="modal" data-target="#exampleModalCenter<%= user.id %>" class="btn-follows btn-search">
              Отписаться
            </a>
            <div class="modal fade" id="exampleModalCenter<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content"> 
                  <div class="modal-exit">
                    <p class="text-center m-0">Вы точно хотите отписаться от пользователя?</p>
                  </div>
                  <div class="modal-footer">
                    <%= link_to "Отмена", "#", class: 'link-exit no-exit', "data-dismiss" => "modal" %>
                    <span class="border-exit"></span>
                    <%= link_to 'Отписаться', follow_toggle_path(user), class: "text-primary link-exit" %>
                  </div>
                </div>
              </div>
            </div>
          <% else %>
            <%= link_to 'Подписаться', follow_toggle_path(user), class: "btn-follows btn-search" %>
          <% end %>
        <% end %> 
      </div>
    <% end %>
  <% end %>
</div>

app/views/searches/phone_search.html.erb
<div id="users" class="container">
  <% if params[:query] == nil %>
    <div class="recomendation">
      Рекомендации
    </div>
      <% if @followers_uniq.present? %>
        <% @followers_uniq.each do |user| %>
          <% unless current_user == user %>  
            <div class="d-flex align-items-center justify-content-between friend">
              <%= link_to(user_path(user.id)) do %>
                <div class="d-flex align-items-center">
                  <% if user.avatar.attached? %>
                    <%= image_tag user.avatar, class: "avatar_in_post rounded-circle float-center mr-3"%> 
                  <% else %>
                    <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center  mr-3") %>
                  <% end %>
                  <div class="nickname_follows">@<%= user.nickname %></div>
                </div>
              <% end %>
              <% if current_user != user %>  
                <% if user.in?(current_user.follows) %>
                  <a href="#" data-toggle="modal" data-target="#exampleModalCenter<%= user.id %>" class="btn-follows btn-search">
                    Отписаться
                  </a>
                  <div class="modal fade" id="exampleModalCenter<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content"> 
                        <div class="modal-exit">
                          <p class="text-center m-0">Вы точно хотите отписаться от пользователя?</p>
                        </div>
                        <div class="modal-footer">
                          <%= link_to "Отмена", "#", class: 'link-exit no-exit', "data-dismiss" => "modal" %>
                          <span class="border-exit"></span>
                          <%= link_to 'Отписаться', follow_toggle_path(user), class: "text-primary link-exit" %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% else %>
                  <%= link_to 'Подписаться', follow_toggle_path(user), class: "btn-follows btn-search" %>
                <% end %>
              <% end %>
            </div>
          <%end%>  
        <%end%>
      <%end%>
  <%else%>
    <% @phones.each do |user| %>
      <div class="d-flex align-items-center justify-content-between friend">
        <%= link_to(user_path(user.id)) do %>
          <div class="d-flex align-items-center">
            <% if user.avatar.attached? %>
              <%= image_tag user.avatar, class: "avatar_in_post rounded-circle float-center mr-3"%> 
            <% else %>
              <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center  mr-3") %>
            <% end %>
            <div class="nickname_follows">@<%= user.nickname %></div>
          </div>
        <% end %>
        <% if current_user != user %>  
          <% if user.in?(current_user.follows) %>
            <a href="#" data-toggle="modal" data-target="#exampleModalCenter<%= user.id %>" class="btn-follows btn-search">
              Отписаться
            </a>
            <div class="modal fade" id="exampleModalCenter<%= user.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content"> 
                  <div class="modal-exit">
                    <p class="text-center m-0">Вы точно хотите отписаться от пользователя?</p>
                  </div>
                  <div class="modal-footer">
                    <%= link_to "Отмена", "#", class: 'link-exit no-exit', "data-dismiss" => "modal" %>
                    <span class="border-exit"></span>
                    <%= link_to 'Отписаться', follow_toggle_path(user), class: "text-primary link-exit" %>
                  </div>
                </div>
              </div>
            </div>
          <% else %>
            <%= link_to 'Подписаться', follow_toggle_path(user), class: "btn-follows btn-search" %>
          <% end %>
        <% end %> 
      </div>
    <% end %>
  <% end %>
</div>