config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/liked_posts', to: 'users#liked_posts'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :users, except: %i[destroy create] do
    member do
      get 'follows'
      get 'followers'
    end
  end
  root 'authentication#show_form'
  get 'authentication/show_form', as: :show_form_in
  post 'authentication/look_for'
  get 'authentication/add_nickname', as: :nickname
  post 'authentication/nickname_exists'
  get 'authentication/code_confirmation'
  post 'authentication/confirmation'
  get 'authentication/open_sess', to: 'authentication#open_sess', as: "open_sess"
  get '/posts/hashtag/:name', to: 'posts#hashtags', as: :hashtag

  resources :posts do
    resources :comments, module: :posts
  end
  
  get 'likes_toggle/:post_id', to: 'users#likes_toggle', as: :likes_toggle
  get 'follow_toggle/:user_id', to: 'users#follow_toggle', as: :follow_toggle
  get 'is_private/:user_id', to: 'users#is_private', as: :is_private
  get 'ask_follow_toggle/:user_id', to: 'users#ask_follow_toggle', as: :ask_follow_toggle
  get 'searches', to: 'searches#index', as: 'searches'
  get 'phones', to: 'searches#phone_search', as: 'phone_search'
  get 'hashtags', to: 'searches#hashtag_search', as: 'hashtag_search'
  delete 'delete_avatar/:upload_id', to: 'users#delete_avatar', as: :delete_avatar
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :description, presence: true, length: { in: 5..500 }
  # validate :correct_image_type

  belongs_to :user

  has_one_attached :picture, dependent: :destroy

  has_one_attached :attachment

  has_and_belongs_to_many :likes, dependent: :nullify,
                                  join_table: :likes,
                                  class_name: 'User'

  has_and_belongs_to_many :tags

  after_commit :create_tag, :on => :create

  def create_tag
    post = Post.find_by(id: self.id)
    hashtags = self.description.scan(/#[A-Za-z0-9А-Яа-я]*/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete("#"))
      post.tags << tag
    end
  end

  before_update do
    post = Post.find_by(id: self.id)
    post.tags.clear
    hashtags = self.description.scan(/#[A-Za-z0-9А-Яа-я]*/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete("#"))
      post.tags << tag
    end
  end

  scope :of_followed_users, ->(following_users) { where user_id: following_users }
  
  has_many :comments, as: :commentable, dependent: :destroy

  private

  def correct_image_type
    # if picture.attached? && !picture.all? {|image| image.content_type.in?( %w( image/jpeg image/png )) }
    #    errors.add(:images , 'Must be a JPEG or a PNG')
    # elsif images.attached? == false
    #   errors.add(:images , 'required')
    # end
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  layout 'authentication'

  before_action :user_log_in?
  before_action :set_post, only: %i[show edit update destroy]

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      upload_attachment
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def index
    id = current_user.follows
    posts_of_friends = Post.of_followed_users(id)
    my_posts = current_user.posts
    @posts = posts_of_friends + my_posts
    @posts.sort! { |a, b| b[:created_at] <=> a[:created_at] }
  end

  def edit; end

  def update
    if @post.update(post_params)
      upload_attachment
      redirect_to user_path(@post.user)
    else
      render :edit
    end
  end

  def hashtags
    tag = Tag.find_by(name: params[:name].downcase)

    @posts = tag.posts.order('created_at DESC')
  end

  def destroy
    @post = Post.destroy(params[:id])
    redirect_back(fallback_location: root_path)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :user_id, :attachment)
  end

  def upload_attachment
    @post.attachment.attach(uploaded_file) if uploaded_file.present?
  end

  def uploaded_file
    params[:post][:attachment]
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
    def render_with_hashtags(description) 
        description.gsub(/#[A-Za-z0-9А-Яа-я]*/){|word| link_to word, "/posts/hashtag/#{word.delete('#')}", class: "hashtag" }.html_safe
    end
end
 

app/views/posts/edit.html.erb
<div class="container">
  <%= form_with url: posts_path, scope: :post, id: "edit_post", local: true do |f| %>
		 <%= f.text_area :description, placeholder: 'Начните писать тут', :class => "input_description" %>
<div class="form-row down">
  <div class="form-group col-md-6">
<%= fa_icon "file-image-o 2x", class: "icon-btn " %>
   <%= f.file_field :attachment, class:"d-none", type: "file", accept:"image/x-png, image/gif, image/jpeg" %> 
   <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group col-md-6">
    	<%= f.submit 'Опубликовать', :class => 'gradient button-send' %> 
  </div>
</div>
  <% end %>
</div>

<script>
 $(".icon-btn").on('click', function() {
   $('#post_attachment').click();
 });
 </script>

app/views/posts/hashtags.html.erb
  <% @posts.each do |post| %>
    <section class='container mt-2 mb-2'>
      <div class="card">
        <div>
          <% if current_user.id == post.user.id %>
            <div class="dropdown">
              <button class="dropdown-toggle border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ...
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'изменить', edit_post_path(post), class: "dropdown-item" %>
                <%= link_to 'удалить', post_path(post), method: :delete, class: "dropdown-item", remote: true %>
              </div>
            </div>
          <% end %>
        </div> 
        <div class="card-body">
          <div class="post_section">
            <div class="post_section">
              <div class="position-relative pr-2">
                <div class="active_user_mini pl-2">
                  
                  <div>
                  <% if post.user.online? %>
                      <i class="fa fa-circle text-success"></i>
                      <% else %>
                      <i class="fa fa-circle text-danger"></i>
                    <% end %>
                    <% if post.user.avatar.attached? %>
                      <%= image_tag post.user.avatar, class: "avatar_in_post rounded-circle float-center" %> 
                    <% else %>
                      <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center") %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="w-100">
              <div class="post_section">
                <p class="nickname_text m-0">
                  <%= link_to user_path(post.user), class: "text-body nickname_text" do %>
                    @<%= post.user.nickname %>
                  <% end %>
                </p>
                <p class="time post_writed">
                  <span class="pr-2 pl-2"><%= show_svg('line2.svg') %></span> <%= post.created_at.strftime("%d.%m.%Y, %H:%M") %>
                </p>
              </div>
              <div class="wrap">
                <div class="card-text post_writed text_wrap mt-3"><%= render_with_hashtags(post.description) %> </div>
              </div>
              <div class="border-0 align-self-center mt-2">     
                <% if post.attachment.attached? %>
                  <% if post.attachment.content_type.include?("image") %>
                    <div class="card_body"> <%= image_tag post.attachment, class: "image text-center"  %> </div>
                  <% else %>
                    <%= video_tag url_for(post.attachment), :controls => true , class: "video" %>
                  <% end %>
                <% end %>
              </div>
              <div class="card-body border-0 align-self-center">
                <div class="post_section mobile_post_section">
                  <div class="comments">
                    <%= link_to(post_path(post)) do %>
                      <p class="icon_text text-center">
                        <span class="none-mobile"><%= show_svg('comment.svg') %></span>
                        <span class="none-desktop"><%= show_svg('comment _mobile.svg') %></span>
                        <%= post.comments.count %> <span class="none-mobile">комментариев</span> 
                      </p> 
                    <% end %>            
                  </div>
                  <div class="likes">
                    <%= link_to(likes_toggle_path(post)) do %>
                      <p class="icon_text  text-center"> 
                        <% if post.likes.ids.include?(current_user.id) %>
                          <span class="none-mobile"><%= show_svg('tenge_active.svg') %></span>
                          <span class="none-desktop"><%= show_svg('tenge_acktive_mobile.svg') %></span>
                        <% else %>
                          <span class="none-mobile"><%= show_svg('tenge_grey.svg') %></span>
                          <span class="none-desktop"><%= show_svg('tenge_mobile.svg') %></span>
                        <% end %>
                        <%= post.likes.count %> <span class="none-mobile">лайкбонусов</span>
                      </p>
                    <% end %>
                  </div>
                </div>
              </div>
              <% if post.comments.any? %>
              <% comment = post.comments.last %>
                <div class="border_on_comment">
                  <div class="post_section">
                    <div class="pr-2">
                      <div class="position-relative">
                        <% if comment.user.avatar.attached? %>
                          <%= image_tag comment.user.avatar, class: "photo_comment rounded-circle float-center" %> 
                        <% else %>
                          <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo_mini rounded-circle float-center") %>
                        <% end %>
                      </div>
                    </div>
                    <div>
                      <div class="post_section">
                        <%= link_to(user_path(post.user)) do %>
                          <p class="nickname_text_comment">
                            @<%= comment.user.nickname %>
                          </p>
                        <% end %>  
                        <p class="time post_writed none-mobile"> | <%= comment.created_at.strftime("%d.%m.%Y, %H:%M") %></p>                      
                        
                      </div>
                      <div class="wrap">
                        <div class="card-text post_writed text_comment text_wrap mt-1"><%= comment.body %> </div>
                        <div class="time post_writed none-desktop"><%= comment.created_at.strftime("%d.%m.%Y, %H:%M") %></div>
                      </div>
                    </div>
                  </div>  
                </div>
              <% end %>  
            </div>
          </div>  
        </div>
        <% if post.comments.any? %>
          <div class="text-center">
            <%= link_to(post_path(post)) do %>
              <p class="all_comments m-0">
                Все комментарии
              </p>
            <% end %>
          </div>
        <% end %>
      </div>
    </section>
  <% end %> 
  <div class="container text-center pb-2 pt-2">
    <div class="text-center pb-1">   
      <%= show_svg('smile.svg') %>
    </div> 
    <p class="smile">Извините, посты кончились. Подпишитесь еще на кого-нибудь</p>
  </div>
</div>

app/views/posts/index.html.erb
<div class="back_container shadow-sm new_post_index">
  <section class="container">
    <div class="new_post">
      <div class="">
        <div class="">
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, class: "photo_mini rounded-circle float-center"%> 
          <% else %>
            <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo_mini rounded-circle float-center") %>
          <% end %>
        </div>
      </div>
      <div class="post_write pl-2">
        <%= form_with url: posts_path, scope: :post, id: "new_post_index", local: true do |f| %>
          <%= f.text_field :description, placeholder: 'Расскажите что-нибудь народу. Напишите пост;)', type: "text", class: "form-control", autocomplete: "off" %>
          <%f.file_field :picture %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <% f.submit %> 
        <% end %>
      </div>          
    </div>
  </section> 
  <% @posts.each do |post| %>
    <section class='container mt-2 mb-2'>
      <div class="card">
        <div>
          <% if current_user.id == post.user.id %>
            <div class="dropdown">
              <button class="dropdown-toggle border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ...
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'изменить', edit_post_path(post), class: "dropdown-item" %>
                <%= link_to 'удалить', post_path(post), method: :delete, class: "dropdown-item", remote: true %>
              </div>
            </div>
          <% end %>
        </div> 
        <div class="card-body">
          <div class="post_section">
            <div class="post_section">
              <div class="position-relative pr-2">
                <div class="active_user_mini pl-2">
                  
                  <div>
                  <% if post.user.online? %>
                      <i class="fa fa-circle text-success"></i>
                      <% else %>
                      <i class="fa fa-circle text-danger"></i>
                    <% end %>
                    <% if post.user.avatar.attached? %>
                      <%= image_tag post.user.avatar, class: "avatar_in_post rounded-circle float-center" %> 
                    <% else %>
                      <%= image_tag("no-foto.png", :alt => "no avatar", class: "avatar_in_post rounded-circle float-center") %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="w-100">
              <div class="post_section">
                <p class="nickname_text m-0">
                  <%= link_to user_path(post.user), class: "text-body nickname_text" do %>
                    @<%= post.user.nickname %>
                  <% end %>
                </p>
                <p class="time post_writed">
                  <span class="pr-2 pl-2"><%= show_svg('line2.svg') %></span> <%= post.created_at.strftime("%d.%m.%Y, %H:%M") %>
                </p>
              </div>
              <div class="wrap">
                <div class="card-text post_writed text_wrap mt-3"><%= render_with_hashtags(post.description)  %> </div>
              </div>
              <div class="border-0 align-self-center mt-2">     
                <% if post.attachment.attached? %>
                  <% if post.attachment.content_type.include?("image") %>
                    <div class="card_body"> <%= image_tag post.attachment, class: "image text-center"  %> </div>
                  <% else %>
                    <%= video_tag url_for(post.attachment), :controls => true , class: "video" %>
                  <% end %>
                <% end %>
              </div>
              <div class="card-body border-0 align-self-center pl-0">
                <div class="post_section mobile_post_section">
                  <div class="comments">
                    <%= link_to(post_path(post)) do %>
                      <p class="icon_text text-center">
                        <span class="none-mobile"><%= show_svg('comment.svg') %></span>
                        <span class="none-desktop"><%= show_svg('comment _mobile.svg') %></span>
                        <%= post.comments.count %> <span class="none-mobile">комментариев</span> 
                      </p> 
                    <% end %>            
                  </div>
                  <div class="likes">
                    <%= link_to(likes_toggle_path(post)) do %>
                      <p class="icon_text  text-center"> 
                        <% if post.likes.ids.include?(current_user.id) %>
                          <span class="none-mobile"><%= show_svg('tenge_active.svg') %></span>
                          <span class="none-desktop"><%= show_svg('tenge_acktive_mobile.svg') %></span>
                        <% else %>
                          <span class="none-mobile"><%= show_svg('tenge_grey.svg') %></span>
                          <span class="none-desktop"><%= show_svg('tenge_mobile.svg') %></span>
                        <% end %>
                        <%= post.likes.count %> <span class="none-mobile">лайкбонусов</span>
                      </p>
                    <% end %>
                  </div>
                </div>
              </div>
              <% if post.comments.any? %>
              <% comment = post.comments.last %>
                <div class="border_on_comment">
                  <div class="post_section">
                    <div class="pr-2">
                      <div class="position-relative">
                        <% if comment.user.avatar.attached? %>
                          <%= image_tag comment.user.avatar, class: "photo_comment rounded-circle float-center" %> 
                        <% else %>
                          <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo_mini rounded-circle float-center") %>
                        <% end %>
                      </div>
                    </div>
                    <div>
                      <div class="post_section">
                        <%= link_to(user_path(post.user)) do %>
                          <p class="nickname_text_comment">
                            @<%= comment.user.nickname %>
                          </p>
                        <% end %>  
                        <p class="time post_writed none-mobile"> | <%= comment.created_at.strftime("%d.%m.%Y, %H:%M") %></p>                      
                        
                      </div>
                      <div class="wrap">
                        <div class="card-text post_writed text_comment text_wrap mt-1"><%= comment.body %> </div>
                        <div class="time post_writed none-desktop"><%= comment.created_at.strftime("%d.%m.%Y, %H:%M") %></div>
                      </div>
                    </div>
                  </div>  
                </div>
              <% end %>  
            </div>
          </div>  
        </div>
        <% if post.comments.any? %>
          <div class="text-center">
            <%= link_to(post_path(post)) do %>
              <p class="all_comments m-0">
                Все комментарии
              </p>
            <% end %>
          </div>
        <% end %>
      </div>
    </section>
  <% end %> 
  <div class="container text-center pb-2 pt-2">
    <div class="text-center pb-1">   
      <%= show_svg('smile.svg') %>
    </div> 
    <p class="smile">Извините, посты кончились. Подпишитесь еще на кого-нибудь</p>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= form_with url: posts_path, scope: :post, id: "new_post", local: true do |f| %>
		 <%= f.text_area :description, placeholder: 'Начните писать тут', :class => "input_description" %>
<div class="form-row down">
  <div class="form-group col-md-6">
   <%= fa_icon "file-image-o 2x", class: "icon-btn " %>
   <%= f.file_field :attachment, class:"d-none", type: "file", accept:"image/x-png, image/gif, image/jpeg" %> 
   <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group col-md-6">
    	<%= f.submit 'Опубликовать', :class => 'gradient button-send' %> 
  </div>
</div>
  <% end %>
</div>

<script>
 $(".icon-btn").on('click', function() {
   $('#post_attachment').click();
 });
 </script>

app/views/posts/show.html.erb
<div class=""> 
  <section class='pb-5'>
    <div class="">
      <div>
        <% if current_user.id == @post.user.id %>
          <div class="dropdown">
            <button class="dropdown-toggle border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              ...
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to 'изменить', edit_post_path(@post), class: "dropdown-item" %>
              <%= link_to 'удалить', post_path(@post), method: :delete, class: "dropdown-item", remote: true %>
            </div>
          </div>
        <% end %>
      </div> 
      <div class="card-body container">
        <div class="post_section">
          <div class="post_section">
            <div class="position-relative pl-2 pr-2">
              <div class="active_user_mini">
                <div>
                  <% if @post.user.avatar.attached? %>
                    <%= image_tag @post.user.avatar, class: "avatar_in_post rounded-circle float-center" %> 
                  <% else %>
                    <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo rounded-circle float-center") %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="w-100">
            <div class="post_section"> 
              <%= link_to(user_path(@post.user)) do %>
                <p class="nickname_text mb-1 pr-1">
                  @<%= @post.user.nickname %>
                </p>
              <% end %>
              <p class="time post_writed">
                <%= show_svg('line2.svg') %> <%= @post.created_at.strftime("%d.%m.%Y,  %H:%M") %>
              </p>
            </div>
            <div class="wrap text_wrap">
              <div class="card-text post_writed text_wrap"><%= render_with_hashtags(@post.description)  %> </div>
            </div>
            <div class="">     
              <% if @post.attachment.attached? %>
                <% if @post.attachment.content_type.include?("image") %>
                  <div class="card_body"> <%= image_tag @post.attachment, class: "image text-center"  %> </div>
                <% else %>
                  <%= video_tag url_for(@post.attachment), :controls => true , class: "video" %>
                <% end %>
              <% end %>
            </div>
            <div class="card-body border-0">
            <div class="post_section mobile_post_section count_likes_comments">
              <div class="comments">
                <p class="icon_text text-center">
                  <span class="none-mobile"><%= show_svg('comment.svg') %></span>
                  <span class="none-desktop"><%= show_svg('comment _mobile.svg') %></span>
                  <%= @post.comments.count %> <span class="none-mobile">комментариев</span> 
                </p>            
              </div>
              <div class="likes">
                <%= link_to(likes_toggle_path(@post)) do %>
                  <p class="icon_text text-center"> 
                  <% if @post.likes.ids.include?(current_user.id) %>
                  <span class="none-mobile"><%= show_svg('tenge_active.svg') %></span>
                <span class="none-desktop"><%= show_svg('tenge_acktive_mobile.svg') %></span>
                  <% else %>
                  <span class="none-mobile"><%= show_svg('tenge_grey.svg') %></span>
                <span class="none-desktop"><%= show_svg('tenge_mobile.svg') %></span>
                  <% end %>
                    <%= @post.likes.count %> <span class="none-mobile">лайкбонусов</span>
                  </p>
                <% end %>
              </div>
            </div>
            <div class="comments-container border-light">
              <%= render @post.comments.where(parent_id: [nil, ""]), max_nesting: 2 %>
            </div>
          </div>
          </div>
        </div>    
      </div>
    </div>
  </section> 
  <div class="container nil"></div>
  <div id="comment_form_down" class="container display_flex between fixed-bottom form_for_comment">
    <div class="pt-2 pr-1">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar, class: "photo_mini rounded-circle float-center photo_input" %> 
      <% else %>
        <%= image_tag("no-foto.png", :alt => "no avatar", class: "photo_mini rounded-circle float-center") %>
      <% end %>
    </div>
    <div class="comment_form_width pb-1">
      <div id="listen"></div>
      <%= render partial: "comments/form", locals: {commentable: @post}  %>
    </div>
  </div>
</div>